- name: Playbook setup_slurm_node
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/slurm.yaml
  tasks:
    - name: Check if setup_slurm_node ran
      ansible.builtin.stat:
        path: /etc/slurm_setup_ran_at
      register: slurm_setup_ran_at_stat
    - name: Don't run if setup_slurm_node already ran
      when: slurm_setup_ran_at_stat.stat.exists
      block:
        - name: Don't run if setup_slurm_node already ran
          debug:
            msg: setup_slurm_node already ran
        - name: End host
          meta: end_host
    - name: Install slurm software prerequisites
      ansible.builtin.include_role:
        name: slurm_r9
        tasks_from: install_prerequisites
    - name: Setup slurm worker node
      ansible.builtin.include_role:
        name: slurm_r9
        tasks_from: setup_node
    # - name: Create slurm_setup_ran_at
    #   ansible.builtin.shell: "date -R > /etc/slurm_setup_ran_at"
