- name: Install packages
  ansible.builtin.dnf:
    state: present
    name:
      - chrony
      - nano
      - mariadb
      - xorg-x11-utils
      - xorg-x11-xauth
      - slurm
      - slurm-doc
      - slurm-slurmctld
      - slurm-slurmd
      - slurm-slurmdbd
      - slurm-slurmrestd
      - slurm-nss_slurm
      - slurm-pam_slurm
      - munge
      - munge-libs
- name: Run mkdir ~/.ssh
  ansible.builtin.command: mkdir -v ~/.ssh
  register: result
  failed_when: not (result.rc == 0 or result.rc == 1)
# - name: Get ssh host keys
#   ansible.builtin.shell: ssh-keyscan {{ item }} >> ~/.ssh/known_hosts
#   with_items:
#     - slurm-c1-head1
#     - slurm-c1-node1
#     - slurm-c1-node2
#     - slurm-c1-node3
#     - slurm-c1-db1
# - name: Sort known_hosts
#   ansible.builtin.shell: |
#     set -o pipefail
#     sort ~/.ssh/known_hosts | uniq > ~/.ssh/known_hosts.unique
# - name: Replace known_hosts with sorted
#   ansible.builtin.command: mv -vf ~/.ssh/known_hosts.unique ~/.ssh/known_hosts
