- name: Copy slurm.conf
  ansible.builtin.template:
    src: etc/slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: u=rw,go=r
- name: Copy slurmdbd.conf
  ansible.builtin.template:
    src: etc/slurm/slurmdbd.conf
    dest: /etc/slurm/slurmdbd.conf
    owner: root
    group: root
    mode: u=rw,go=
- name: Start slurmd
  ansible.builtin.systemd:
    name: slurmd
    enabled: true
    state: restarted
